AWSTemplateFormatVersion: '2010-09-09'

Description: Cloudformation template to create an S3 bucket with private access control.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-s3-youtube-bucket-test
      AccessControl: Private